MVC_CodeFirstApproach_20_Ausgust/MVCAppWithAuthentication/MVCAppWithAuthentication/Controllers/CustmoersController.cs
using MVCAppWithAuthentication.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCAppWithAuthentication.Controllers
{
    public class CustmoersController : Controller
    {
        private ApplicationDbContext _context;
            
        public CustmoersController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Custmoers
        public ActionResult Index()
        {
            var customers = _context.customers.Include(c=>c.
            MemberShipType).ToList();
            return View(customers);
        }

        public ActionResult Details(int id)
        {
            var singleCustomer = _context.customers.Include(c => c.
            MemberShipType).SingleOrDefault(c => c.Id==id);
            if(singleCustomer==null)
            {
                return HttpNotFound();
            }
            return View(singleCustomer);
        }
    }
}

MVC_CodeFirstApproach_20_Ausgust/MVCAppWithAuthentication/MVCAppWithAuthentication/Views/Custmoers/Details.cshtml
@model MVCAppWithAuthentication.Models.Customers
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customer Details</h2>

<table class="table tab-content table-bordered table-responsive"
    <tr>
        <td>Name</td>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <td>Membershiptype</td>
        <td>@Model.MemberShipType.DisCountRate</td>
    </tr>
    <tr>
        <td>Date Of Birth</td>
        <td>@Model.DateOfBirth</td>
    </tr>
</table>
<br />
<h4>@Html.CheckBoxFor(c => c.IsSubscribedToNewsLetter)</h4>

MVC_CodeFirstApproach_20_Ausgust/MVCAppWithAuthentication/MVCAppWithAuthentication/Views/Custmoers/Index.cshtml
@model IEnumerable<MVCAppWithAuthentication.Models.Customers>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<table class="table tab-content table-bordered table-responsive">
    <tr>
        <td>Customer Name</td>
        <td>Discount Rate</td>
        
    </tr>
    @foreach (var c in Model)
    {
        <tr>
            <td>@Html.ActionLink(c.Name, "Details","Custmoers",
               new { id = c.Id},null)</td>
            <td>@c.MemberShipType.DisCountRate</td>
        </tr>
    }
</table>